// Deterministic source scheduler fixture. Generated bytecode only; the separate
// archive checks read the owned script.img without exporting payload bytes.
#include "app/platform/linux/NativeScriptSession.h"

#include <algorithm>
#include <bit>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

namespace {
using Bytes = std::vector<std::uint8_t>;
std::size_t s_Checks = 0;

void Check(bool condition, const char* message) {
    ++s_Checks;
    if (!condition) {
        std::fprintf(stderr, "native-script-scheduling FAIL: %s\n", message);
        std::exit(1);
    }
}

void Put(Bytes& bytes, std::uint32_t value, unsigned count) {
    for (unsigned i = 0; i < count; ++i) bytes.push_back(std::uint8_t(value >> (8 * i)));
}

void Patch(Bytes& bytes, std::size_t offset, std::uint32_t value) {
    for (unsigned i = 0; i < 4; ++i) bytes.at(offset + i) = std::uint8_t(value >> (8 * i));
}

void Op(Bytes& bytes, std::uint16_t opcode) { Put(bytes, opcode, 2); }
void I8(Bytes& bytes, std::int8_t value) { bytes.push_back(4); Put(bytes, std::uint8_t(value), 1); }
void I16(Bytes& bytes, std::int16_t value) { bytes.push_back(5); Put(bytes, std::uint16_t(value), 2); }
void I32(Bytes& bytes, std::int32_t value) { bytes.push_back(1); Put(bytes, std::uint32_t(value), 4); }
void F(Bytes& bytes, float value) { bytes.push_back(6); Put(bytes, std::bit_cast<std::uint32_t>(value), 4); }
void Global(Bytes& bytes, std::uint16_t offset) { bytes.push_back(2); Put(bytes, offset, 2); }
void Local(Bytes& bytes, std::uint16_t index) { bytes.push_back(3); Put(bytes, index, 2); }
void Array(Bytes& bytes, bool global, std::uint16_t base, bool globalIndex,
    std::uint16_t index, std::uint8_t count, bool floating = false) {
    bytes.push_back(global ? 7 : 8); Put(bytes, base, 2); Put(bytes, index, 2); Put(bytes, count, 1);
    Put(bytes, (globalIndex ? 0x80 : 0) | (floating ? 1 : 0), 1);
}
void EndArguments(Bytes& bytes) { bytes.push_back(0); }

struct StreamDefinition {
    std::string Name;
    std::uint32_t Size = 0;
};

std::uint32_t FixtureCodeStart(std::size_t missions, std::size_t streams) {
    return 104 + std::uint32_t(missions) * 4 + std::uint32_t(streams) * 28;
}

Bytes Fixture(const Bytes& code, const std::vector<Bytes>& missions,
    const std::vector<StreamDefinition>& streams) {
    Bytes result;
    auto chunk = [&](std::uint8_t index, const Bytes& payload) {
        const auto next = std::uint32_t(result.size() + payload.size() + 8);
        Op(result, 2); I32(result, std::int32_t(next)); result.push_back(index);
        result.insert(result.end(), payload.begin(), payload.end());
    };
    chunk(115, Bytes(16));
    chunk(0, Bytes(4));
    Bytes info(16);
    const auto codeStart = FixtureCodeStart(missions.size(), streams.size());
    const auto mainSize = codeStart + std::uint32_t(code.size());
    Patch(info, 0, mainSize);
    Patch(info, 8, std::uint32_t(missions.size()));
    std::uint32_t missionOffset = mainSize, largestMission = 0;
    for (const auto& mission : missions) {
        Put(info, missionOffset, 4);
        missionOffset += std::uint32_t(mission.size());
        largestMission = std::max(largestMission, std::uint32_t(mission.size()));
    }
    Patch(info, 4, largestMission);
    Patch(info, 12, missions.empty() ? 0 : 1024);
    chunk(1, info);
    Bytes streamed(8);
    std::uint32_t largestStream = 0, logicalOffset = 0;
    Patch(streamed, 4, std::uint32_t(streams.size()));
    for (const auto& definition : streams) {
        Check(!definition.Name.empty() && definition.Name.size() < 20, "generated streamed name capacity");
        for (unsigned i = 0; i < 20; ++i)
            streamed.push_back(i < definition.Name.size() ? std::uint8_t(definition.Name[i]) : 0);
        Put(streamed, logicalOffset, 4);
        Put(streamed, definition.Size, 4);
        logicalOffset += definition.Size;
        largestStream = std::max(largestStream, definition.Size);
    }
    Patch(streamed, 0, largestStream);
    chunk(2, streamed);
    chunk(3, Bytes(4));
    Bytes extra(8); Patch(extra, 0, 16); chunk(4, extra);
    Check(result.size() == codeStart, "generated scheduling header size");
    result.insert(result.end(), code.begin(), code.end());
    for (const auto& mission : missions) result.insert(result.end(), mission.begin(), mission.end());
    return result;
}

struct Services final : NativeScriptServices {
    NativeScriptServiceResult RequestCollision(const NativeScriptCollisionRequest&) override { return {}; }
    NativeScriptServiceResult LoadScene(const NativeScriptSceneRequest&) override { return {}; }
    NativeScriptServiceResult CreatePlayer(const NativeScriptPlayerRequest&) override { return {}; }
};

struct Event {
    std::uint32_t Pass = 0, Time = 0, Thread = 0, IP = 0;
    std::uint64_t Generation = 0;
    std::uint16_t Opcode = 0;
    std::uint8_t StackDepth = 0;
    NativeScriptThreadForm Form = NativeScriptThreadForm::Main;
    bool operator==(const Event&) const = default;
};

struct Sink final : NativeScriptCommitSink {
    std::uint32_t Pass = 0;
    std::vector<Event> Events;
    Sink() { Events.reserve(32); }
    void OnScriptCommit(NativeScriptRequestId, std::size_t threadIndex,
        const NativeScriptState&, const NativeScriptThreadState& thread) noexcept override {
        Events.push_back({Pass, thread.TimeMs, std::uint32_t(threadIndex), thread.LastInstructionIP,
            thread.Generation, thread.LastOpcode, thread.StackDepth,
            thread.IsExternal ? NativeScriptThreadForm::Streamed :
                thread.ThisMustBeTheOnlyMissionRunning ? NativeScriptThreadForm::Mission :
                    NativeScriptThreadForm::Main});
    }
};

struct RouteResult {
    std::vector<Event> Events;
    std::array<std::size_t, 6> Executed{};
    bool operator==(const RouteResult&) const = default;
};

RouteResult RunRoute() {
    Bytes external;
    Op(external, 0x0050); const auto externalSubPatch = external.size() + 1; I32(external, 0);
    Op(external, 0x0001); I8(external, 4);
    Op(external, 0x004E);
    const auto externalSub = std::uint32_t(external.size());
    Op(external, 0x0006); Local(external, 10); I32(external, 410);
    Op(external, 0x0051);
    Patch(external, externalSubPatch, std::uint32_t(-std::int32_t(externalSub)));

    Bytes mission;
    Op(mission, 0x0050); const auto missionSubPatch = mission.size() + 1; I32(mission, 0);
    Op(mission, 0x0001); I8(mission, 3);
    Op(mission, 0x004E);
    const auto missionSub = std::uint32_t(mission.size());
    Op(mission, 0x0006); Local(mission, 10); I32(mission, 310);
    Op(mission, 0x0051);
    Patch(mission, missionSubPatch, std::uint32_t(-std::int32_t(missionSub)));

    Bytes code;
    Op(code, 0x0050); const auto gosubPatch = code.size() + 1; I32(code, 0);
    Op(code, 0x004F); const auto childPatch = code.size() + 1; I32(code, 0);
    I32(code, 41); I8(code, -7); I16(code, -1234); F(code, 1.25f);
    Global(code, 8); Local(code, 0); Array(code, true, 16, true, 12, 2);
    Array(code, false, 4, false, 1, 4); EndArguments(code);
    Op(code, 0x0913); I8(code, 0); I8(code, -3); F(code, 2.5f); Local(code, 0); EndArguments(code);
    Op(code, 0x0417); I8(code, 0);
    Op(code, 0x0001); I8(code, 5);
    Op(code, 0x004E);
    const auto subOffset = std::uint32_t(code.size());
    Op(code, 0x0006); Local(code, 0); I32(code, 11);
    Op(code, 0x0006); Local(code, 1); I32(code, 1);
    Op(code, 0x0006); Local(code, 5); I32(code, 88);
    Op(code, 0x0004); Global(code, 8); I32(code, 77);
    Op(code, 0x0004); Global(code, 12); I32(code, 1);
    Op(code, 0x0004); Global(code, 20); I32(code, 99);
    Op(code, 0x0051);
    const auto childOffset = std::uint32_t(code.size());
    Op(code, 0x0001); I8(code, 2);
    Op(code, 0x004E);
    const auto codeStart = FixtureCodeStart(1, 1);
    Patch(code, gosubPatch, codeStart + subOffset);
    Patch(code, childPatch, codeStart + childOffset);

    const auto payload = Fixture(code, {mission}, {{"TEST_STREAM", std::uint32_t(external.size())}});
    NativeScriptSession session;
    Services services;
    std::string error;
    Check(session.LoadMainBytes(payload, payload.size(), error), "load deterministic scheduling fixture");
    const auto unloaded = session.StreamedScripts().front();
    Bytes wrong = external; wrong.push_back(0);
    Check(!session.LoadStreamedScriptBytes(0, wrong, error) && session.StreamedScripts().front() == unloaded,
        "streamed payload size rejection is atomic");
    Check(session.LoadStreamedScriptBytes(0, external, error), "load generated streamed payload");
    Check(session.StreamedScripts()[0].Loaded && session.StreamedScripts()[0].Generation == 1 &&
        session.StreamedScripts()[0].Users == 0, "initial streamed generation owner");

    Sink sink;
    RouteResult route;
    auto pass = [&](std::uint32_t number, std::uint32_t time, std::size_t expected) {
        if (time != session.State().TimeMs) Check(session.AdvanceTime(time, error), "advance deterministic script time");
        sink.Pass = number;
        const auto result = session.RunPass(services, 100, &sink);
        if (result.Status != NativeScriptStatus::Waiting || result.Executed != expected) {
            std::fprintf(stderr, "pass=%u time=%u status=%u executed=%zu thread=%zu ip=%u opcode=%04X message=%s\n",
                number, time, unsigned(result.Status), result.Executed, result.ThreadIndex,
                result.IP, result.Opcode, result.Message.c_str());
            for (const auto& event : sink.Events)
                std::fprintf(stderr, " event pass=%u thread=%u ip=%u op=%04X stack=%u\n",
                    event.Pass, event.Thread, event.IP, event.Opcode, event.StackDepth);
        }
        Check(result.Status == NativeScriptStatus::Waiting && result.Executed == expected,
            "deterministic pass reaches wait boundary");
        route.Executed[number - 1] = result.Executed;
    };
    pass(1, 0, 18); // six SCM chunk GOTOs plus twelve scheduling/stack commands
    Check(session.Threads().size() == 4, "main child streamed and mission thread slots");
    Check(session.Threads()[0].StackDepth == 0 && session.Threads()[0].ReturnStack[0] == 0 &&
        session.Threads()[0].Locals[0] == 11, "GOSUB RETURN stack and local mutation");
    Check(session.Threads()[1].Locals[0] == 41 &&
        session.Threads()[1].Locals[1] == std::uint32_t(std::int32_t(-7)) &&
        session.Threads()[1].Locals[2] == std::uint32_t(std::int32_t(-1234)) &&
        session.Threads()[1].Locals[3] == std::bit_cast<std::uint32_t>(1.25f) &&
        session.Threads()[1].Locals[4] == 77 && session.Threads()[1].Locals[5] == 11 &&
        session.Threads()[1].Locals[6] == 99 && session.Threads()[1].Locals[7] == 88,
        "all source numeric variadic handoff forms");
    Check(session.Threads()[2].IsExternal && session.Threads()[2].StreamedIndex == 0 &&
        session.Threads()[2].StreamedGeneration == 1 && session.Threads()[2].BaseIP == 300000 &&
        session.Threads()[2].Locals[0] == std::uint32_t(std::int32_t(-3)) &&
        session.Threads()[2].Locals[1] == std::bit_cast<std::uint32_t>(2.5f) &&
        session.Threads()[2].Locals[2] == 11, "streamed thread identity and variadic handoff");
    Check(session.Threads()[3].ThisMustBeTheOnlyMissionRunning && session.Threads()[3].BaseIP == 200000 &&
        session.Threads()[3].Locals.size() == 1024, "exclusive mission thread owner");
    Check(session.StreamedScripts()[0].Users == 1, "streamed user acquired at launch");
    Check(!session.UnloadStreamedScript(0, error) && session.StreamedScripts()[0].Users == 1,
        "live streamed payload cannot evict");

    NativeScriptCorpusManifest manifest;
    for (std::size_t thread = 0; thread < session.Threads().size(); ++thread) {
        NativeScriptInstructionForm form;
        Check(session.InspectInstruction(thread, form, error) && manifest.Observe(form, error),
            "classify all scheduled thread forms");
    }
    const auto summary = manifest.Summary();
    Check(summary.Threads == 4 && summary.MainSites == 2 && summary.MissionSites == 1 &&
        summary.StreamedSites == 1, "main mission streamed corpus identity");

    pass(2, 0, 9);
    Check(sink.Events.size() == 27 && sink.Events[18].Thread == 3 && sink.Events[22].Thread == 2 &&
        sink.Events[26].Thread == 1, "new threads run next pass in head insertion order");
    Check(session.Threads()[2].StackDepth == 0 && session.Threads()[2].Locals[10] == 410 &&
        session.Threads()[3].StackDepth == 0 && session.Threads()[3].Locals[10] == 310,
        "base-relative streamed and mission GOSUB RETURN");
    pass(3, 2, 1);
    pass(4, 3, 1);
    pass(5, 4, 1);
    Check(session.StreamedScripts()[0].Users == 0, "streamed termination releases user");
    pass(6, 5, 1);
    Check(std::ranges::all_of(session.Threads(), [](const auto& thread) { return !thread.Active; }),
        "all deterministic fixture threads terminate");
    Check(session.UnloadStreamedScript(0, error) && !session.StreamedScripts()[0].Loaded,
        "zero-user streamed payload evicts");
    Check(session.LoadStreamedScriptBytes(0, external, error) && session.StreamedScripts()[0].Generation == 2,
        "streamed reload advances generation");
    route.Events = std::move(sink.Events);
    return route;
}

void VariadicClassification() {
    Bytes code;
    Op(code, 0x004F); const auto childPatch = code.size() + 1; I32(code, 0);
    I32(code, 1); I8(code, 2); I16(code, 3); F(code, 4.0f);
    Global(code, 8); Local(code, 0); Array(code, true, 8, true, 12, 2);
    Array(code, false, 4, false, 1, 4); EndArguments(code);
    Op(code, 0x0001); I8(code, 1);
    const auto childOffset = std::uint32_t(code.size());
    Op(code, 0x004E);
    Patch(code, childPatch, FixtureCodeStart(0, 0) + childOffset);
    const auto payload = Fixture(code, {}, {});
    NativeScriptSession session;
    Services services;
    std::string error;
    Check(session.LoadMainBytes(payload, payload.size(), error), "load variadic classification fixture");
    const auto headers = session.RunPass(services, 6);
    Check(headers.Status == NativeScriptStatus::BudgetYield && headers.Executed == 6,
        "variadic fixture reaches executable code");
    NativeScriptInstructionForm form;
    Check(session.InspectInstruction(0, form, error), "inspect START_NEW_SCRIPT variadic form");
    Check(form.Opcode == 0x004F && form.FixedOperandCount == 1 && form.OperandCount == 9 &&
        form.VariadicArguments && form.OperandTags[0] == 1 && form.OperandTags[1] == 1 &&
        form.OperandTags[2] == 4 && form.OperandTags[3] == 5 && form.OperandTags[4] == 6 &&
        form.OperandTags[5] == 2 && form.OperandTags[6] == 3 && form.OperandTags[7] == 7 &&
        form.OperandTags[8] == 8, "exact fixed and tag-zero-terminated operand form");
    Check(std::ranges::all_of(form.OperandTypes.begin() + 1, form.OperandTypes.begin() + 9,
        [](auto type) { return type == NativeScriptOperandType::Argument; }),
        "variadic union operands are not assigned invented scalar types");
    Check(form.ArrayCounts[7] == 2 && form.ArrayFlags[7] == 0x80 &&
        form.ArrayCounts[8] == 4 && form.ArrayFlags[8] == 0, "exact variadic array metadata");
    NativeScriptCorpusManifest manifest;
    Check(manifest.Observe(form, error) && manifest.Summary().OperandForms == 1,
        "corpus accepts classified variadic source form");
}

void Faults() {
    Services services;
    std::string error;
    const auto reachCode = [&](NativeScriptSession& session) {
        const auto headers = session.RunPass(services, 6);
        Check(headers.Status == NativeScriptStatus::BudgetYield && headers.Executed == 6,
            "fixture header traversal reaches executable code");
    };
    Bytes underflow; Op(underflow, 0x0051);
    const auto underflowPayload = Fixture(underflow, {}, {});
    NativeScriptSession underflowSession;
    Check(underflowSession.LoadMainBytes(underflowPayload, underflowPayload.size(), error), "load stack underflow fixture");
    reachCode(underflowSession);
    const auto underflowState = underflowSession.State();
    Check(underflowSession.RunPass(services, 1).Status == NativeScriptStatus::Error &&
        static_cast<const NativeScriptThreadState&>(underflowSession.State()) ==
            static_cast<const NativeScriptThreadState&>(underflowState), "RETURN underflow faults without commit");

    Bytes overflow;
    const auto targetPatch = overflow.size() + 3;
    Op(overflow, 0x0050); I32(overflow, 0);
    Patch(overflow, targetPatch, FixtureCodeStart(0, 0));
    const auto overflowPayload = Fixture(overflow, {}, {});
    NativeScriptSession overflowSession;
    Check(overflowSession.LoadMainBytes(overflowPayload, overflowPayload.size(), error), "load stack overflow fixture");
    reachCode(overflowSession);
    const auto overflowResult = overflowSession.RunPass(services, 9);
    Check(overflowResult.Status == NativeScriptStatus::Error && overflowResult.Executed == 8 &&
        overflowSession.Threads()[0].StackDepth == 8, "GOSUB fixed stack depth eight");

    Bytes unloaded;
    Op(unloaded, 0x0913); I8(unloaded, 0); EndArguments(unloaded);
    const auto unloadedPayload = Fixture(unloaded, {}, {{"NOT_LOADED", 2}});
    NativeScriptSession unloadedSession;
    Check(unloadedSession.LoadMainBytes(unloadedPayload, unloadedPayload.size(), error), "load unloaded streamed fixture");
    reachCode(unloadedSession);
    Check(unloadedSession.RunPass(services, 1).Status == NativeScriptStatus::Error &&
        unloadedSession.Threads().size() == 1 && !unloadedSession.StreamedScripts()[0].Loaded,
        "0913 rejects an unloaded script before thread creation");

    Bytes tooMany;
    Op(tooMany, 0x004F); const auto tooManyTarget = tooMany.size() + 1; I32(tooMany, 0);
    for (unsigned i = 0; i < 33; ++i) I8(tooMany, std::int8_t(i));
    EndArguments(tooMany);
    const auto tooManyChild = std::uint32_t(tooMany.size());
    Op(tooMany, 0x004E);
    Patch(tooMany, tooManyTarget, FixtureCodeStart(0, 0) + tooManyChild);
    const auto tooManyPayload = Fixture(tooMany, {}, {});
    NativeScriptSession tooManySession;
    Check(tooManySession.LoadMainBytes(tooManyPayload, tooManyPayload.size(), error),
        "load oversized argument fixture");
    reachCode(tooManySession);
    const auto tooManyState = tooManySession.State();
    Check(tooManySession.RunPass(services, 1).Status == NativeScriptStatus::Error &&
        static_cast<const NativeScriptThreadState&>(tooManySession.State()) ==
            static_cast<const NativeScriptThreadState&>(tooManyState) && tooManySession.Threads().size() == 1,
        "thirty-third child argument rejects before thread creation");
}

void RealArchive(const char* gameDir) {
    NativeScriptSession session;
    std::string error;
    Check(session.LoadMain(gameDir, error), "load real main streamed metadata");
    Check(session.StreamedScripts().size() == 79, "real streamed metadata count");
    const auto& first = session.StreamedScripts().front().Definition;
    Check(std::string(first.Name.data()) == "PLAYER_PARACHUTE" && first.FileOffset == 3079744 &&
        first.Size == 5631, "real streamed metadata first identity");
    const auto before = session.StreamedScripts().front();
    Check(!session.LoadStreamedScript("/missing-native-script-root", 0, error) &&
        session.StreamedScripts().front() == before, "missing streamed IMG retains owner");
    Check(session.LoadStreamedScript(gameDir, 0, error), "load real PLAYER_PARACHUTE IMG member");
    Check(session.StreamedScripts()[0].Loaded && session.StreamedScripts()[0].Generation == 1 &&
        session.StreamedScripts()[0].Users == 0, "real streamed payload generation");
    Check(!session.LoadStreamedScript(gameDir, 0, error) && session.StreamedScripts()[0].Generation == 1,
        "duplicate real streamed load rejected");
    Check(session.UnloadStreamedScript(0, error) && !session.StreamedScripts()[0].Loaded,
        "real streamed payload unload");
    const auto& last = session.StreamedScripts().back().Definition;
    Check(std::string(last.Name.data()) == "AAA" && last.FileOffset == 0 && last.Size == 8,
        "real streamed metadata sentinel identity");
    Check(session.LoadStreamedScript(gameDir, 78, error) && session.StreamedScripts()[78].Loaded,
        "name-mapped archive order loads AAA");
    Check(session.UnloadStreamedScript(78, error), "unload real AAA payload");
}
} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::fprintf(stderr, "usage: %s <owned-game-dir>\n", argv[0]);
        return 2;
    }
    const auto first = RunRoute();
    const auto second = RunRoute();
    Check(first == second, "scheduler fixture ordering is identical twice");
    Check(first.Executed == std::array<std::size_t, 6>{18, 9, 1, 1, 1, 1} && first.Events.size() == 31,
        "deterministic scheduler pass shape");
    VariadicClassification();
    Faults();
    RealArchive(argv[1]);
    std::printf("sa-core-scheduling-ok checks=%zu commits=%zu passes=18,9,1,1,1,1 "
        "threads=main,mission,streamed stack=8 streamed=79 deterministic=twice\n",
        s_Checks, first.Events.size());
    return 0;
}
