#include "app/platform/linux/NativeScriptSchema.h"

namespace {
using O = NativeScriptOperandType;
using C = NativeScriptSemanticCoverage;

// Sanny Builder Library sa/sa.json, default extension, pinned rather than read
// at runtime. Behavioral ownership is verified independently against game_sa.
constexpr NativeScriptOpcodeSchema s_Schema[]{
    {0x09F5, {O::Integer}, 1, C::Implemented},
    {0x0000, {}, 0, C::Implemented},
    {0x0001, {O::Integer}, 1, C::Implemented}, {0x0002, {O::Integer}, 1, C::Implemented},
    {0x0004, {O::Output, O::Integer}, 2, C::Implemented}, {0x0005, {O::FloatOutput, O::Float}, 2, C::Implemented},
    {0x0006, {O::Output, O::Integer}, 2, C::Implemented}, {0x0007, {O::FloatOutput, O::Float}, 2, C::Implemented},
    {0x0086, {O::FloatOutput, O::Float}, 2, C::Implemented},
    {0x0008, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x0009, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x000A, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x000B, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x000C, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x000D, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x000E, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x000F, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x0010, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x0011, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x0012, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x0013, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x0014, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x0015, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x0016, {O::InOutInteger, O::Integer}, 2, C::Implemented}, {0x0017, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x001A, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x004F, {O::Integer}, 1, C::Implemented, true},
    {0x0050, {O::Integer}, 1, C::Implemented}, {0x0051, {}, 0, C::Implemented},
    {0x004D, {O::Integer}, 1, C::Implemented}, {0x004E, {}, 0, C::Implemented},
    {0x00C5, {}, 0, C::Unsupported}, {0x00C6, {}, 0, C::Unsupported},
    {0x00D6, {O::Integer}, 1, C::Implemented}, {0x03A4, {O::String}, 1, C::Implemented},
    {0x054C, {O::String}, 1, C::Implemented},
    {0x03E0, {O::Integer}, 1, C::Implemented},
    {0x0A0F, {}, 0, C::Implemented},
    {0x03E6, {}, 0, C::Implemented},
    {0x016A, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x042C, {O::Integer}, 1, C::Implemented}, {0x030D, {O::Integer}, 1, C::Implemented},
    {0x0997, {O::Integer}, 1, C::Implemented}, {0x01F0, {O::Integer}, 1, C::Implemented},
    {0x0111, {O::Integer}, 1, C::Implemented}, {0x0112, {}, 0, C::Implemented},
    {0x00C0, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x04E4, {O::Float, O::Float}, 2, C::Implemented},
    {0x03CB, {O::Float, O::Float, O::Float}, 3, C::Implemented},
    {0x062A, {O::Integer, O::Float}, 2, C::Implemented},
    {0x0629, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0053, {O::Integer, O::Float, O::Float, O::Float, O::Output}, 5, C::Implemented},
    {0x06CF, {O::Integer}, 1, C::Implemented},
    {0x0746, {O::Integer, O::Integer, O::Integer}, 3, C::Implemented},
    {0x07AF, {O::Integer, O::Output}, 2, C::Implemented},
    {0x01F5, {O::Integer, O::Output}, 2, C::Implemented},
    {0x0373, {}, 0, C::Implemented}, {0x0173, {O::Integer, O::Float}, 2, C::Implemented},
    {0x0417, {O::Integer}, 1, C::Implemented}, {0x06C8, {O::Integer}, 1, C::Implemented},
    {0x0517, {O::Float, O::Float, O::Float, O::String, O::Output}, 5, C::Implemented},
    {0x0518, {O::Float, O::Float, O::Float, O::Integer, O::String, O::Output}, 6, C::Implemented},
    {0x0570, {O::Float, O::Float, O::Float, O::Integer, O::Output}, 5, C::Implemented},
    {0x04CE, {O::Float, O::Float, O::Float, O::Integer, O::Output}, 5, C::Implemented},
    {0x018B, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x09B4, {O::Float, O::Float, O::Float, O::Integer, O::Integer}, 5, C::Implemented},
    {0x02B9, {O::String}, 1, C::Implemented},
    {0x016C, {O::Float, O::Float, O::Float, O::Float, O::Integer}, 5, C::Implemented},
    {0x016D, {O::Float, O::Float, O::Float, O::Float, O::Integer}, 5, C::Implemented},
    {0x0213, {O::Integer, O::Integer, O::Float, O::Float, O::Float, O::Output}, 6, C::Implemented},
    {0x0214, {O::Integer}, 1, C::Implemented}, {0x0215, {O::Integer}, 1, C::Implemented},
    {0x014B, {O::Float, O::Float, O::Float, O::Float, O::Integer, O::Integer, O::Integer,
              O::Integer, O::Integer, O::Integer, O::Integer, O::Integer, O::Output}, 13, C::Implemented},
    {0x014C, {O::Integer, O::Integer}, 2, C::Implemented},
    // Streamed registration opcodes are genuine source NOPs. 0913 starts an
    // already-loaded script and copies its tag-zero-terminated arguments.
    {0x0911, {}, 0, C::Implemented},
    {0x0913, {O::Integer}, 1, C::Implemented, true},
    // Registration is owned separately from runtime update/reward/reset/save.
    {0x0814, {O::Float, O::Float, O::Float, O::Float, O::Float, O::Float,
               O::Float, O::Float, O::Float, O::Float, O::Float, O::Float,
               O::Float, O::Float, O::Float, O::Integer}, 16, C::Implemented},
    // CREATE_OBJECT_NO_OFFSET is owned as a source identity/lifetime record;
    // model streaming/render/world cleanup remain separate consumers.
    {0x029B, {O::Integer, O::Float, O::Float, O::Float, O::Output}, 5, C::Implemented},
    {0x0177, {O::Integer, O::Float}, 2, C::Implemented},
    {0x01C7, {O::Integer}, 1, C::Implemented},
    {0x07F7, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0550, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0107, {O::Integer, O::Float, O::Float, O::Float, O::Output}, 5, C::Implemented},
    {0x0392, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x09CA, {O::Integer, O::Integer, O::Integer, O::Integer, O::Integer, O::Integer}, 6, C::Implemented},
    {0x034D, {O::Integer, O::Float, O::Float, O::Integer}, 4, C::Implemented},
    {0x02FA, {O::String, O::Integer}, 2, C::Implemented},
    {0x0566, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x01BB, {O::Integer, O::FloatOutput, O::FloatOutput, O::FloatOutput}, 4, C::Implemented},
    {0x0176, {O::Integer, O::FloatOutput}, 2, C::Implemented},
    {0x0827, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0381, {O::Integer, O::Float, O::Float, O::Float}, 4, C::Implemented},
    {0x0400, {O::Integer, O::Float, O::Float, O::Float, O::FloatOutput, O::FloatOutput,
              O::FloatOutput}, 7, C::Implemented},
    {0x0453, {O::Integer, O::Float, O::Float, O::Float}, 4, C::Implemented},
    {0x0A17, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x09E2, {O::Float, O::Float, O::Float, O::Float, O::Integer, O::Integer, O::Integer,
              O::Integer, O::Integer, O::Integer, O::Integer, O::Integer, O::String, O::Output},
              14, C::Implemented},
    {0x07FB, {O::String, O::Integer}, 2, C::Implemented},
    {0x04F8, {O::Integer, O::Float, O::Float, O::Float, O::Float, O::Float, O::Float,
              O::Float, O::Float, O::Float, O::Float, O::Float, O::Float}, 13, C::Implemented},
    {0x08CA, {}, 0, C::Implemented},
    {0x0767, {O::String, O::Integer}, 2, C::Implemented},
    {0x0874, {O::String, O::Integer}, 2, C::Implemented},
    {0x076A, {O::String, O::Integer}, 2, C::Implemented},
    {0x076C, {O::String, O::Integer, O::Integer}, 3, C::Implemented},
    {0x09B7, {O::String, O::Integer}, 2, C::Implemented},
    {0x0959, {O::Float, O::Float, O::Float, O::Output}, 4, C::Implemented},
    {0x095A, {O::Float, O::Float, O::Float, O::Output}, 4, C::Implemented},
    {0x0958, {O::Float, O::Float, O::Float, O::Output}, 4, C::Implemented},
    {0x032B, {O::Integer, O::Integer, O::Integer, O::Float, O::Float, O::Float, O::Output}, 7, C::Implemented},
    {0x0180, {O::Output}, 1, C::Implemented},
    {0x04AE, {O::Output, O::Integer}, 2, C::Implemented},
    {0x04AF, {O::Output, O::Integer}, 2, C::Implemented},
    {0x01E7, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float},6,C::Implemented},
    {0x01E8, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float},6,C::Implemented},
    {0x091D, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float},6,C::Implemented},
    {0x091E, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float},6,C::Implemented},
    {0x022A, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float},6,C::Implemented},
    {0x022B, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float},6,C::Implemented},
    {0x02A7, {O::Float,O::Float,O::Float,O::Integer,O::Output},5,C::Implemented},
    {0x04A6, {O::Float,O::Float,O::Float,O::Integer,O::Integer,O::Output},6,C::Unsupported},
    {0x0662, {O::IgnoredString},1,C::Implemented},
    {0x0914, {O::Argument},1,C::Implemented},
    {0x0929, {O::Integer,O::Integer,O::Integer,O::Float,O::Integer},5,C::Implemented},
    {0x0928, {O::Integer,O::Integer,O::Integer},3,C::Implemented},
    {0x07D3, {O::Integer, O::String}, 2, C::Implemented},
    {0x0884, {O::Integer, O::String}, 2, C::Implemented},
    {0x08E8, {O::Integer, O::String}, 2, C::Implemented},
    {0x0776, {O::String}, 1, C::Implemented},
    {0x0777, {O::String}, 1, C::Implemented},
    {0x0363, {O::Float, O::Float, O::Float, O::Float, O::Integer, O::Integer}, 6, C::Implemented},
    {0x00D7, {O::Integer}, 1, C::Implemented},
    {0x09BA, {O::Integer}, 1, C::Implemented},
    {0x0256, {O::Integer}, 1, C::Implemented},
    {0x01B6, {O::Integer}, 1, C::Implemented},
    {0x087B, {O::Integer, O::String, O::String, O::Integer}, 4, C::Implemented},
    {0x070D, {O::Integer}, 1, C::Implemented},
    {0x0793, {}, 0, C::Implemented},
    {0x0169, {O::Integer, O::Integer, O::Integer}, 3, C::Implemented},
    {0x04BB, {O::Integer}, 1, C::Implemented},
    {0x01B4, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x01B7, {}, 0, C::Implemented},
    {0x077E, {O::Output}, 1, C::Implemented},
    {0x0652, {O::Integer, O::Output}, 2, C::Implemented},
    {0x07D0, {O::Output}, 1, C::Implemented},
    {0x09FB, {O::Output}, 1, C::Implemented},
    {0x0842, {O::Integer, O::Output}, 2, C::Implemented},
    {0x01BD, {O::Output}, 1, C::Implemented},
    {0x0038, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0084, {O::Output, O::Integer}, 2, C::Implemented},
    {0x0060, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x0028, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x03B0, {O::String}, 1, C::Implemented},
    {0x0926, {O::Integer, O::Output}, 2, C::Implemented},
    {0x08A9, {O::Integer}, 1, C::Implemented},
    {0x08AB, {O::Integer}, 1, C::Implemented},
    {0x090F, {O::Integer}, 1, C::Implemented},
    {0x0491, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0018, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x00BF, {O::Output, O::Output}, 2, C::Unsupported},
    {0x00EC, {O::Integer, O::Float, O::Float, O::Float, O::Float, O::Integer}, 6, C::Implemented},
    {0x0871, {O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,
        O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 18, C::Implemented},
    {0x0872, {O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,
        O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 18, C::Implemented},
    {0x00BA, {O::String, O::Integer, O::Integer}, 3, C::Unsupported},
    {0x00A3, {O::Integer, O::Float, O::Float, O::Float, O::Float, O::Integer}, 6, C::Implemented},
    {0x04A3, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x00FE, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Implemented},
    {0x001C, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x00FF, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Implemented},
    {0x03EE, {O::Integer}, 1, C::Implemented},
    {0x0956, {O::Output}, 1, C::Unsupported},
    {0x00BE, {}, 0, C::Implemented},
    {0x00BC, {O::String, O::Integer, O::Integer}, 3, C::Implemented},
    {0x03E5, {O::String}, 1, C::Unsupported},
    {0x00DF, {O::Integer}, 1, C::Implemented},
    {0x03C0, {O::Integer, O::Output}, 2, C::Implemented},
    {0x096E, {O::Integer}, 1, C::Unsupported},
    {0x0164, {O::Integer}, 1, C::Implemented},
    {0x02A3, {O::Integer}, 1, C::Implemented},
    {0x015F, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float}, 6, C::Implemented},
    {0x0160, {O::Float, O::Float, O::Float, O::Integer}, 4, C::Implemented},
    {0x0395, {O::Float, O::Float, O::Float, O::Float, O::Integer}, 5, C::Implemented},
    {0x05D3, {O::Integer,O::Float,O::Float,O::Float,O::Integer,O::Integer}, 6, C::Implemented},
    {0x0811, {O::Integer, O::Output}, 2, C::Unsupported},
    {0x08EC, {O::Integer, O::Output}, 2, C::Unsupported},
    {0x09E8, {O::Integer, O::Output}, 2, C::Implemented},
    {0x0A2D, {O::Integer}, 1, C::Unsupported},
    {0x09BE, {}, 0, C::Unsupported},
    {0x08B4, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0602, {O::Integer}, 1, C::Unsupported},
    {0x00DD, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x056C, {O::Integer}, 1, C::Unsupported},
    {0x02BF, {O::Integer}, 1, C::Unsupported},
    {0x0596, {O::Integer}, 1, C::Unsupported},
    {0x08FE, {}, 0, C::Unsupported},
    {0x00E1, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0981, {O::Integer}, 1, C::Unsupported},
    {0x03D5, {O::String}, 1, C::Implemented},
    {0x097A, {O::Float, O::Float, O::Float, O::Integer}, 4, C::Implemented},
    {0x0A40, {O::Float, O::Float, O::Float, O::Integer, O::Output}, 5, C::Implemented},
    {0x0A41, {O::Integer}, 1, C::Implemented},
    {0x058C, {O::FloatOutput}, 1, C::Implemented},
    {0x0394, {O::Integer}, 1, C::Unsupported},
    {0x030C, {O::Integer}, 1, C::Unsupported},
    {0x002A, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x08E1, {O::Output}, 1, C::Implemented},
    {0x0237, {O::Integer, O::Integer, O::Integer, O::Integer}, 4, C::Unsupported},
    {0x0030, {O::Float, O::Float}, 2, C::Implemented},
    {0x0109, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x08E2, {O::Output}, 1, C::Unsupported},
    {0x094A, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x04F9, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x057E, {O::Integer}, 1, C::Unsupported},
    {0x0860, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x00A1, {O::Integer, O::Float, O::Float, O::Float}, 4, C::Unsupported},
    {0x02EB, {}, 0, C::Implemented},
    {0x04FA, {O::Integer}, 1, C::Unsupported},
    {0x002C, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x03D8, {}, 0, C::Unsupported},
    {0x03D9, {}, 0, C::Unsupported},
    {0x016B, {}, 0, C::Implemented},
    {0x0687, {O::Integer}, 1, C::Unsupported},
    {0x0512, {O::String}, 1, C::Unsupported},
    {0x0965, {O::Integer}, 1, C::Implemented},
    {0x03E7, {O::Integer}, 1, C::Unsupported},
    {0x047A, {O::Integer}, 1, C::Unsupported},
    {0x02D8, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x03CF, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x03D0, {O::Integer}, 1, C::Implemented},
    {0x03D1, {O::Integer}, 1, C::Implemented},
    {0x03D2, {O::Integer}, 1, C::Implemented},
    {0x0459, {O::String}, 1, C::Implemented},
    {0x0792, {O::Integer}, 1, C::Unsupported},
    {0x08F8, {O::Integer}, 1, C::Implemented},
    {0x0039, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x008B, {O::Output, O::Integer}, 2, C::Implemented},
    {0x005A, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x001E, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0340, {O::Integer, O::Integer, O::Integer, O::Integer}, 4, C::Implemented},
    {0x060D, {O::Integer, O::Integer, O::Integer, O::Integer, O::Integer}, 5, C::Implemented},
    {0x033E, {O::Float, O::Float, O::String}, 3, C::Implemented},
    {0x0019, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x045A, {O::Float, O::Float, O::String, O::Integer}, 4, C::Unsupported},
    {0x008A, {O::Output, O::Integer}, 2, C::Implemented},
    {0x03E4, {O::Integer}, 1, C::Unsupported},
    {0x0341, {O::Integer}, 1, C::Implemented},
    {0x0343, {O::Float}, 1, C::Implemented},
    {0x0344, {O::Float}, 1, C::Implemented},
    {0x0348, {O::Integer}, 1, C::Implemented},
    {0x0345, {O::Integer}, 1, C::Implemented},
    {0x033F, {O::Float, O::Float}, 2, C::Implemented},
    {0x0342, {O::Integer}, 1, C::Implemented},
    {0x081C, {O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 5, C::Unsupported},
    {0x0349, {O::Integer}, 1, C::Implemented},
    {0x0904, {O::Integer,O::Output,O::Output,O::Output,O::Output}, 5, C::Unsupported},
    {0x03CA, {O::Integer}, 1, C::Implemented},
    {0x0471, {O::Integer,O::Integer,O::Float,O::Float,O::Integer}, 5, C::Implemented},
    {0x07D6, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x044B, {O::Integer}, 1, C::Unsupported},
    {0x0A03, {}, 0, C::Unsupported},
    {0x010F, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0208, {O::Float, O::Float, O::FloatOutput}, 3, C::Unsupported},
    {0x005B, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x0025, {O::Float, O::Float}, 2, C::Implemented},
    {0x0023, {O::Float, O::Float}, 2, C::Implemented},
    {0x0087, {O::Float, O::Float}, 2, C::Unsupported},
    {0x0063, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x0073, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x01FB, {O::Float, O::FloatOutput}, 2, C::Unsupported},
    {0x006B, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x04D9, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0382, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x04DA, {O::Integer}, 1, C::Unsupported},
    {0x0085, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0062, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x0093, {O::Float, O::Integer}, 2, C::Unsupported},
    {0x0088, {O::Float, O::Float}, 2, C::Unsupported},
    {0x005F, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x006D, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x005D, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x0815, {O::Integer, O::Float, O::Float, O::Float}, 4, C::Unsupported},
    {0x076F, {}, 0, C::Unsupported},
    {0x0984, {O::Integer, O::Output}, 2, C::Unsupported},
    {0x0248, {O::Integer}, 1, C::Implemented},
    {0x097B, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x02FD, {O::String,O::Integer,O::Integer,O::Integer,O::Integer}, 5, C::Unsupported},
    {0x008F, {O::Float, O::Integer}, 2, C::Unsupported},
    {0x0424, {}, 0, C::Implemented},
    {0x0425, {O::Float, O::FloatOutput}, 2, C::Unsupported},
    {0x0628, {O::Integer, O::Float}, 2, C::Unsupported},
    {0x050A, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::FloatOutput}, 7, C::Unsupported},
    {0x0065, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x01BC, {O::Integer, O::Float, O::Float, O::Float}, 4, C::Unsupported},
    {0x03C3, {O::Integer, O::Integer, O::String}, 3, C::Unsupported},
    {0x04F7, {O::Integer, O::Integer, O::Integer, O::String}, 4, C::Unsupported},
    {0x018A, {O::Float, O::Float, O::Float, O::Output}, 4, C::Unsupported},
    {0x075C, {O::Integer}, 1, C::Implemented},
    {0x0058, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x005E, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x001B, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x080A, {O::Integer,O::Integer,O::FloatOutput,O::FloatOutput,O::FloatOutput}, 5, C::Unsupported},
    {0x02CE, {O::Float, O::Float, O::Float, O::FloatOutput}, 4, C::Unsupported},
    {0x0509, {O::Float,O::Float,O::Float,O::Float,O::FloatOutput}, 5, C::Unsupported},
    {0x0089, {O::Float, O::Float}, 2, C::Unsupported},
    {0x008E, {O::Integer, O::Float}, 2, C::Unsupported},
    {0x006A, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x0092, {O::Integer, O::Float}, 2, C::Unsupported},
    {0x01E3, {O::String,O::Integer,O::Integer,O::Integer}, 4, C::Unsupported},
    {0x0627, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0151, {O::Integer}, 1, C::Unsupported},
    {0x014F, {O::Integer}, 1, C::Unsupported},
    {0x00A5, {O::Integer,O::Float,O::Float,O::Float,O::Output}, 5, C::Implemented},
    {0x009A, {O::Integer,O::Integer,O::Float,O::Float,O::Float,O::Output}, 6, C::Implemented},
    {0x056E, {O::Integer}, 1, C::Unsupported},
    {0x0119, {O::Integer}, 1, C::Implemented},
    {0x00AA, {O::Integer,O::FloatOutput,O::FloatOutput,O::FloatOutput}, 4, C::Unsupported},
    {0x01EB, {O::Float}, 1, C::Implemented},
    {0x03DE, {O::Float}, 1, C::Implemented},
    {0x04ED, {O::String}, 1, C::Unsupported},
    {0x04EE, {O::String}, 1, C::Unsupported},
    {0x020A, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0221, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x02AC, {O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 6, C::Unsupported},
    {0x0615, {O::Output}, 1, C::Unsupported},
    {0x0812, {O::Integer,O::String,O::String,O::Float,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 9, C::Unsupported},
    {0x0643, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0616, {O::Integer}, 1, C::Unsupported},
    {0x0118, {O::Integer}, 1, C::Implemented},
    {0x0A32, {O::Integer}, 1, C::Unsupported},
    {0x0618, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0137, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x096D, {O::Integer, O::Integer, O::Output}, 3, C::Unsupported},
    {0x0953, {O::Output}, 1, C::Implemented},
    {0x04A4, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0736, {O::Integer}, 1, C::Unsupported},
    {0x07B1, {O::Integer,O::Output,O::Output,O::Output}, 4, C::Unsupported},
    {0x09EE, {O::Integer}, 1, C::Unsupported},
    {0x003B, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x01AD, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Integer}, 6, C::Unsupported},
    {0x07D5, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float}, 7, C::Unsupported},
    {0x0803, {O::Integer}, 1, C::Unsupported},
    {0x07F5, {O::Integer,O::Float,O::Float,O::Float,O::Float}, 5, C::Unsupported},
    {0x003A, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x061B, {O::Integer}, 1, C::Unsupported},
    {0x0611, {O::Integer, O::String}, 2, C::Unsupported},
    {0x0613, {O::Integer, O::String, O::FloatOutput}, 3, C::Unsupported},
    {0x062E, {O::Integer, O::Integer, O::Output}, 3, C::Unsupported},
    {0x0955, {}, 0, C::Implemented},
    {0x04EF, {O::String}, 1, C::Unsupported},
    {0x0209, {O::Integer, O::Integer, O::Output}, 3, C::Unsupported},
    {0x015B, {O::Integer, O::Integer, O::Integer}, 3, C::Unsupported},
    {0x005C, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x0029, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0494, {O::Integer,O::Output,O::Output,O::Output,O::Output}, 5, C::Unsupported},
    {0x0021, {O::Float, O::Float}, 2, C::Implemented},
    {0x05A4, {O::Float,O::Float,O::Float,O::Float,O::FloatOutput}, 5, C::Unsupported},
    {0x040D, {O::Integer}, 1, C::Implemented},
    {0x05AA, {O::StringOutput, O::String}, 2, C::Implemented},
    {0x094E, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0A09, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x094D, {O::Integer}, 1, C::Unsupported},
    {0x0949, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0967, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x05AE, {O::String, O::String}, 2, C::Unsupported},
    {0x056D, {O::Integer}, 1, C::Unsupported},
    {0x094F, {O::Integer}, 1, C::Unsupported},
    {0x0968, {O::Integer}, 1, C::Unsupported},
    {0x03F0, {O::Integer}, 1, C::Implemented},
    {0x0390, {O::String}, 1, C::Implemented},
    {0x038F, {O::Integer, O::String}, 2, C::Implemented},
    {0x09FA, {}, 0, C::Unsupported},
    {0x006F, {O::InOutFloat, O::Float}, 2, C::Implemented},
    {0x03E3, {O::Integer}, 1, C::Unsupported},
    {0x038D, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Integer,O::Integer,O::Integer,O::Integer}, 9, C::Unsupported},
    {0x0391, {}, 0, C::Implemented},
    {0x002B, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x001D, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0072, {O::InOutInteger, O::Integer}, 2, C::Implemented},
    {0x05A9, {O::StringOutput, O::String}, 2, C::Implemented},
    {0x0108, {O::Integer}, 1, C::Unsupported},
    {0x0519, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x02CA, {O::Integer}, 1, C::Unsupported},
    {0x00A6, {O::Integer}, 1, C::Implemented},
    {0x0798, {O::Integer,O::Output,O::Output,O::Output}, 4, C::Unsupported},
    {0x0799, {O::Integer}, 1, C::Unsupported},
    {0x073E, {O::Float,O::Float,O::Float,O::Float,O::Integer,O::Output}, 6, C::Unsupported},
    {0x01C1, {O::Integer}, 1, C::Unsupported},
    {0x01F3, {O::Integer}, 1, C::Implemented},
    {0x003C, {O::Integer, O::Integer}, 2, C::Implemented},
    {0x0441, {O::Integer, O::Output}, 2, C::Unsupported},
    {0x0431, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0376, {O::Float,O::Float,O::Float,O::Output}, 4, C::Unsupported},
    {0x0430, {O::Integer,O::Integer,O::Integer}, 3, C::Implemented},
    {0x0337, {O::Integer, O::Integer}, 2, C::Unsupported},
    {0x0432, {O::Integer,O::Integer,O::Output}, 3, C::Unsupported},
    {0x009B, {O::Integer}, 1, C::Implemented},
    {0x00BB, {O::String,O::Integer,O::Integer}, 3, C::Unsupported},
    {0x0103, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Implemented},
    {0x0797, {O::Integer,O::Float}, 2, C::Unsupported},
    {0x00A0, {O::Integer,O::FloatOutput,O::FloatOutput,O::FloatOutput}, 4, C::Implemented},
    {0x00AB, {O::Integer,O::Float,O::Float,O::Float}, 4, C::Unsupported},
    {0x0227, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x0091, {O::Float,O::Integer}, 2, C::Unsupported},
    {0x07E4, {O::Integer,O::FloatOutput,O::FloatOutput,O::FloatOutput,O::FloatOutput,O::FloatOutput,O::FloatOutput}, 7, C::Unsupported},
    {0x02F6, {O::Float,O::FloatOutput}, 2, C::Unsupported},
    {0x02F7, {O::Float,O::FloatOutput}, 2, C::Unsupported},
    {0x0175, {O::Integer,O::Float}, 2, C::Implemented},
    {0x00DB, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x05CD, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x07CC, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0581, {O::Integer}, 1, C::Unsupported},
    {0x08D4, {O::String,O::Float,O::Float,O::Float,O::Integer,O::Integer,O::Integer,O::Integer,O::Output}, 9, C::Unsupported},
    {0x08DB, {O::Integer,O::Integer,O::String,O::String,O::String,O::String,O::String,O::String,O::String,O::String,
        O::String,O::String,O::String,O::String,O::String}, 15, C::Unsupported},
    {0x090E, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x08D7, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x08DA, {O::Integer}, 1, C::Unsupported},
    {0x09E1, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x0090, {O::Integer,O::Float}, 2, C::Unsupported},
    {0x08EE, {O::Integer,O::Integer,O::Integer,O::String,O::Integer}, 5, C::Unsupported},
    {0x010B, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x0247, {O::Integer}, 1, C::Implemented},
    {0x0878, {O::Integer,O::Float}, 2, C::Unsupported},
    {0x0249, {O::Integer}, 1, C::Implemented},
    {0x0229, {O::Integer,O::Integer,O::Integer}, 3, C::Unsupported},
    {0x0623, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x01AF, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Unsupported},
    {0x00C2, {O::Float,O::Float,O::Float,O::Float}, 4, C::Unsupported},
    {0x01C3, {O::Integer}, 1, C::Implemented},
    {0x03A9, {}, 0, C::Implemented},
    {0x05B6, {O::DebugString128}, 1, C::Implemented},
    {0x03A7, {O::Integer}, 1, C::Implemented},
    {0x0202, {O::Integer,O::Integer,O::Float,O::Float,O::Integer}, 5, C::Unsupported},
    {0x0674, {O::Integer,O::String}, 2, C::Unsupported},
    {0x03FE, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x01C5, {O::Integer}, 1, C::Unsupported},
    {0x0762, {O::Integer}, 1, C::Unsupported},
    {0x060B, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x02A9, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0104, {O::Integer,O::Integer,O::Float,O::Float,O::Float,O::Integer}, 6, C::Unsupported},
    {0x051A, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x077A, {O::Integer,O::Integer,O::Integer}, 3, C::Unsupported},
    {0x074F, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x04B5, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0A2A, {O::String}, 1, C::Unsupported},
    {0x034E, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Unsupported},
    {0x04E6, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Unsupported},
    {0x08BA, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x06D1, {O::StringOutput,O::String}, 2, C::Implemented},
    {0x08C0, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x08B5, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x08BB, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x08C1, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x0101, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Unsupported},
    {0x08B6, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x0632, {O::Integer}, 1, C::Unsupported},
    {0x07B4, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0A43, {}, 0, C::Unsupported},
    {0x08BC, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x093A, {O::String,O::Integer}, 2, C::Unsupported},
    {0x0750, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x08E0, {O::Float,O::Float,O::Float,O::Float,O::Float}, 5, C::Unsupported},
    {0x08DE, {O::Integer}, 1, C::Unsupported},
    {0x08DF, {O::Float,O::Float,O::Float,O::Float,O::Float}, 5, C::Unsupported},
    {0x08DD, {O::Integer}, 1, C::Unsupported},
    {0x0625, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0064, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x00A4, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Unsupported},
    {0x0361, {O::String}, 1, C::Unsupported},
    {0x0043, {O::Float,O::Float}, 2, C::Implemented},
    {0x00C1, {O::Integer,O::Integer,O::Output}, 3, C::Unsupported},
    {0x01B2, {O::Integer,O::Integer,O::Integer}, 3, C::Unsupported},
    {0x01B9, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x02E2, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0978, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x0709, {O::Integer,O::Integer,O::Integer,O::Float,O::Float,O::Float,O::Float,O::Integer,O::Integer}, 9, C::Unsupported},
    {0x0350, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0446, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0568, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x02AB, {O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 6, C::Unsupported},
    {0x0223, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x05BA, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x065C, {O::Integer}, 1, C::Unsupported},
    {0x01C2, {O::Integer}, 1, C::Implemented},
    {0x034F, {O::Integer}, 1, C::Unsupported},
    {0x0500, {O::Integer,O::Integer,O::String}, 3, C::Unsupported},
    {0x0095, {O::Output}, 1, C::Unsupported},
    {0x001F, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x08C2, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x091A, {O::IgnoredString}, 1, C::Implemented},
    {0x0846, {O::String}, 1, C::Implemented},
    {0x08F9, {O::String,O::String}, 2, C::Unsupported},
    {0x091B, {}, 0, C::Unsupported},
    {0x0663, {O::DebugString,O::Integer}, 2, C::Unsupported},
    {0x07E5, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x094B, {O::Integer, O::StringOutput}, 2, C::Implemented},
    {0x01C0, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x07B0, {O::String}, 1, C::Unsupported},
    {0x038B, {}, 0, C::Unsupported},
    {0x09F2, {O::Integer}, 1, C::Unsupported},
    {0x0708, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x010E, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x002F, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x0445, {}, 0, C::Implemented},
    {0x09AE, {O::Integer}, 1, C::Implemented},
    {0x04C8, {O::Integer}, 1, C::Implemented},
    {0x04A7, {O::Integer}, 1, C::Implemented},
    {0x09E7, {O::Integer}, 1, C::Implemented},
    {0x04FC, {O::Integer,O::Output,O::FloatOutput,O::Output,O::FloatOutput,O::Output,O::FloatOutput}, 7, C::Implemented},
    {0x0020, {O::Float,O::Float}, 2, C::Implemented},
    {0x008C, {O::InOutInteger,O::Float}, 2, C::Implemented},
    {0x008D, {O::InOutFloat,O::Integer}, 2, C::Implemented},
    {0x0061, {O::InOutFloat,O::Float}, 2, C::Implemented},
    {0x0302, {O::String,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 7, C::Unsupported},
    {0x02FF, {O::String,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 6, C::Unsupported},
    {0x0174, {O::Integer,O::FloatOutput}, 2, C::Unsupported},
    {0x020D, {O::Integer}, 1, C::Unsupported},
    {0x0022, {O::Float,O::Float}, 2, C::Implemented},
    {0x0059, {O::InOutFloat,O::Float}, 2, C::Implemented},
    {0x0024, {O::Float,O::Float}, 2, C::Implemented},
    {0x09AB, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0068, {O::InOutInteger,O::Integer}, 2, C::Implemented},
    {0x01E4, {O::String,O::Integer,O::Integer,O::Integer}, 4, C::Unsupported},
    {0x0308, {O::String,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer,O::Integer}, 9, C::Unsupported},
    {0x042D, {O::Integer,O::Output}, 2, C::Unsupported},
    // CARMOD1's skipped vehicle-customisation branch: classified exactly so
    // source GOTO targets are provable, never executed as unknown NOPs.
    {0x0448, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x0969, {O::Integer}, 1, C::Unsupported},
    {0x0975, {O::Integer}, 1, C::Unsupported},
    {0x096F, {O::Integer}, 1, C::Unsupported},
    {0x09BD, {O::Integer}, 1, C::Unsupported},
    {0x0A26, {}, 0, C::Unsupported},
    {0x09B3, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x0A19, {O::String}, 1, C::Unsupported},
    {0x0840, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x075E, {O::String}, 1, C::Unsupported},
    {0x075D, {O::String}, 1, C::Unsupported},
    {0x075F, {O::Output}, 1, C::Unsupported},
    {0x03F3, {O::Integer,O::Output,O::Output}, 3, C::Unsupported},
    {0x0988, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x09FE, {O::Integer}, 1, C::Unsupported},
    {0x096B, {}, 0, C::Unsupported},
    {0x096C, {}, 0, C::Unsupported},
    {0x0A13, {}, 0, C::Unsupported},
    {0x087C, {}, 0, C::Unsupported},
    {0x0100, {O::Integer,O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer}, 8, C::Unsupported},
    {0x06E9, {O::Integer}, 1, C::Unsupported},
    {0x06EA, {O::Integer}, 1, C::Unsupported},
    {0x06ED, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x06E7, {O::Integer,O::Integer,O::Output}, 3, C::Unsupported},
    {0x06EB, {O::Integer}, 1, C::Unsupported},
    {0x0A22, {O::Integer,O::Integer,O::Integer,O::Integer}, 4, C::Unsupported},
    {0x0624, {O::Integer,O::Float}, 2, C::Unsupported},
    {0x09D4, {}, 0, C::Unsupported},
    {0x0A30, {O::Integer}, 1, C::Unsupported},
    {0x0790, {O::Integer}, 1, C::Unsupported},
    {0x05AD, {O::String,O::String}, 2, C::Unsupported},
    // INTRO1 skipped cutscene body: exact forms establish GOSUB boundaries;
    // none become executable semantics through classification alone.
    {0x02E4, {O::String}, 1, C::Implemented},
    {0x06B9, {}, 0, C::Implemented},
    {0x02E7, {}, 0, C::Implemented},
    {0x02E9, {}, 0, C::Implemented},
    {0x02EA, {}, 0, C::Implemented},
    {0x056A, {}, 0, C::Implemented},
    {0x0A0B, {O::Float,O::Float,O::Float,O::Float}, 4, C::Implemented},
    {0x023C, {O::Integer,O::String}, 2, C::Implemented},
    {0x07C0, {O::Integer}, 1, C::Implemented},
    {0x07C1, {O::Integer}, 1, C::Implemented},
    {0x023D, {O::Integer}, 1, C::Implemented},
    {0x0952, {O::Integer}, 1, C::Implemented},
    {0x09C8, {}, 0, C::Implemented},
    {0x06D7, {O::Integer}, 1, C::Implemented},
    {0x067F, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x0129, {O::Integer,O::Integer,O::Integer,O::Output}, 4, C::Implemented},
    {0x01C8, {O::Integer,O::Integer,O::Integer,O::Integer,O::Output}, 5, C::Implemented},
    {0x060E, {O::Integer}, 1, C::Implemented},
    {0x05EB, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x0954, {}, 0, C::Implemented},
    {0x06D8, {O::Integer,O::Float,O::Float,O::Float,O::Integer,O::Output}, 6, C::Implemented},
    {0x06DC, {O::Integer,O::Float}, 2, C::Implemented},
    {0x06DD, {O::Integer,O::Float}, 2, C::Implemented},
    {0x0707, {O::Integer}, 1, C::Implemented},
    {0x099A, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x0622, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x0701, {}, 0, C::Implemented},
    {0x06D9, {}, 0, C::Implemented},
    {0x0296, {O::Integer}, 1, C::Implemented},
    {0x0925, {}, 0, C::Implemented},
    {0x092F, {O::Integer}, 1, C::Implemented},
    {0x0930, {O::Integer}, 1, C::Implemented},
    {0x0936, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer,O::Integer}, 8, C::Implemented},
    {0x0920, {O::Float,O::Float,O::Float,O::Float,O::Float,O::Float,O::Integer,O::Integer}, 8, C::Implemented},
    {0x09B2, {O::Integer,O::Output,O::Output}, 3, C::Implemented},
    {0x0560, {O::Integer,O::Output}, 2, C::Implemented},
    {0x05D1, {O::Integer,O::Integer,O::Float,O::Float,O::Float,O::Float,O::Integer,O::Integer,O::Integer}, 9, C::Implemented},
    {0x099C, {O::Integer,O::Float,O::Float}, 3, C::Implemented},
    {0x015A, {}, 0, C::Implemented},
    {0x0362, {O::Integer,O::Float,O::Float,O::Float}, 4, C::Unsupported},
    {0x041D, {O::Float}, 1, C::Implemented},
    {0x02A8, {O::Float,O::Float,O::Float,O::Integer,O::Output}, 5, C::Implemented},
    {0x0330, {O::Integer,O::Integer}, 2, C::Implemented},
    {0x048F, {O::Integer}, 1, C::Implemented},
    {0x0186, {O::Integer,O::Output}, 2, C::Unsupported},
    {0x07E0, {O::Integer,O::Integer}, 2, C::Unsupported},
    {0x00D8, {}, 0, C::Implemented},
    {0x0653, {O::Integer,O::FloatOutput}, 2, C::Unsupported},
    {0x08DC, {O::Integer,O::Float,O::Float,O::Float}, 4, C::Unsupported},
    {0x0299, {O::String}, 1, C::Unsupported},
    {0x0317, {}, 0, C::Implemented},
};
}

std::span<const NativeScriptOpcodeSchema> NativeScriptSchemaEntries() noexcept { return s_Schema; }

const NativeScriptOpcodeSchema* NativeScriptLookupSchema(std::uint16_t opcode) noexcept {
    for (const auto& schema : s_Schema) {
        if (schema.Opcode == opcode) return &schema;
    }
    return nullptr;
}

std::string_view NativeScriptSchemaRevision() noexcept { return "53ed1c2561bf6ca70dc16afca5d8f3a406066158"; }
std::string_view NativeScriptSchemaSha256() noexcept { return "797f32be6d3ebae87fd65b57ccc0c0b1cbc2e129c089668761e366740b5bd671"; }
std::string_view NativeScriptSchemaVersion() noexcept { return "1.65"; }
