// Differential oracle uses actual upstream function bodies, generated by the
// companion Python runner. This executable is not part of the runtime target.
#include "app/platform/linux/NativeTransmission.h"
#include "NativeTransmissionOracle.h"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

static void Check(bool condition,const char* message) {
    if (!condition) { std::fprintf(stderr,"transmission FAIL %s\n",message); std::exit(1); }
}
static void Equal(float a,float b,const char* message) {
    if (std::abs(a-b)>2e-6f*std::max({1.0f,std::abs(a),std::abs(b)})) {
        std::fprintf(stderr,"actual=%.9g source=%.9g ",a,b); Check(false,message);
    }
}
static oracle::cTransmission Original(NativeTransmission::Config config) {
    oracle::tHandlingData h;
    auto& t=h.Transmission;
    t.m_EngineAcceleration=config.EngineAcceleration*0.4f;
    t.m_EngineInertia=config.EngineInertia;
    t.m_MaxVelocity=config.MaxVelocityKmh;
    t.m_nNumberOfGears=config.NumberOfGears;
    t.m_nDriveType=config.DriveType;
    t.m_handlingFlags=config.HandlingFlags;
    h.m_fDragMult=config.Drag;
    h.m_bUseMaxspLimit=(config.HandlingFlags&0x1000000u)!=0;
    oracle::cHandlingDataMgr{}.ConvertDataToGameUnits(&h);
    return t;
}
int main(int argc,char** argv) {
    Check(argc==2,"handling.cfg argument");
    std::ifstream file(argv[1]); std::string line;
    std::vector<std::string> row;
    while (std::getline(file,line)) {
        std::istringstream stream(line); row.clear();
        for (std::string token;stream>>token;) row.push_back(token);
        if (!row.empty() && row[0]=="LANDSTAL") break;
    }
    Check(row.size()>=33 && row[0]=="LANDSTAL","read real LANDSTAL");
    const NativeTransmission::Config config{std::stof(row[12]),std::stof(row[13]),std::stof(row[14]),std::stof(row[3]),
        static_cast<std::uint8_t>(std::stoi(row[11])),row[15][0],static_cast<std::uint32_t>(std::stoul(row[32],nullptr,16))};
    NativeTransmission landstal; landstal.Initialize(config);
    Equal(landstal.EngineAcceleration,25.0f*0.4f/2500.0f/4.0f,"LANDSTAL file->game acceleration (not 25 SI)");
    Equal(landstal.EngineAcceleration*4*50*50,10.0f,"driven-wheel and game->SI units before gear/throttle factor");
    std::printf("LANDSTAL fileAccel=%.3f gameAccel=%.9f flatMs=%.6f maxMs=%.6f reverseMs=%.6f flags=%x\n",
        config.EngineAcceleration,landstal.EngineAcceleration,landstal.MaxFlatVelocity*50,landstal.MaxVelocity*50,landstal.MaxReverseVelocity*50,config.HandlingFlags);
    int comparisons=0;
    for (auto drive:{'4','F','R'}) for (int gears=1;gears<=5;++gears)
    for (unsigned flags:{0u,1u,2u,0x1000002u}) for (float drag:{0.005f,0.01f,2.5f,20.0f}) {
        auto c=config; c.DriveType=drive; c.NumberOfGears=gears; c.HandlingFlags=flags; c.Drag=drag;
        NativeTransmission native; native.Initialize(c); auto original=Original(c);
        Equal(native.EngineAcceleration,original.m_EngineAcceleration,"converted acceleration");
        Equal(native.MaxVelocity,original.m_MaxVelocity,"converted maximum");
        Equal(native.MaxFlatVelocity,original.m_MaxFlatVelocity,"drag-limited flat maximum");
        Equal(native.MaxReverseVelocity,original.m_MaxReverseVelocity,"reverse maximum");
        for (int g=0;g<=gears;++g) {
            Equal(native.Gears[g].MaxVelocity,original.m_aGears[g].MaxVelocity,"gear max");
            Equal(native.Gears[g].ChangeUpVelocity,original.m_aGears[g].ChangeUpVelocity,"gear up");
            Equal(native.Gears[g].ChangeDownVelocity,original.m_aGears[g].ChangeDownVelocity,"gear down");
            for (float v:{native.MaxReverseVelocity-0.001f,native.MaxReverseVelocity,0.0f,-0.011f,
                          native.Gears[g].ChangeUpVelocity-0.0001f,native.Gears[g].ChangeUpVelocity+0.0001f,
                          native.Gears[g].ChangeDownVelocity-0.0001f,native.Gears[g].ChangeDownVelocity+0.0001f,
                          native.MaxVelocity,native.MaxVelocity+0.001f})
            for (float gas:{-1.0f,0.0f,0.35f,1.0f}) for (float step:{0.25f,1.0f,1.6666667f}) for (bool grounded:{false,true}) {
                NativeTransmission::State s{static_cast<std::uint8_t>(g),0.3f,0.6f};
                auto gear=s.CurrentGear; float ratio=s.InertiaRatio,smoother=s.InertiaSmoother,count=0,speed=v;
                oracle::CTimer::Step=step;
                const float expected=original.CalculateDriveAcceleration(gas,gear,count,speed,&ratio,&smoother,grounded,0);
                Equal(native.DriveAcceleration(gas,s,v,step,grounded),expected,"per-wheel drive increment");
                Check(s.CurrentGear==gear,"up/down/reverse shift");
                Equal(s.InertiaRatio,ratio,"persistent inertia ratio");
                Equal(s.InertiaSmoother,smoother,"persistent inertia smoothing");
                ++comparisons;
            }
        }
    }
    auto original=Original(config);
    NativeTransmission::State state;
    oracle::uint8 gear=1; float ratio=0,smoother=0,count=0,expected=0,speed=0;
    oracle::CTimer::Step=50.0f/30.0f;
    for (int tick=1;tick<=900;++tick) {
        const auto before=state.CurrentGear;
        speed+=landstal.DriveAcceleration(1,state,speed/50,NativeTransmission::TimeStep)*landstal.DrivenWheels()*50;
        speed=landstal.AirResistance(speed,NativeTransmission::TimeStep);
        float gameSpeed=expected/50;
        expected+=original.CalculateDriveAcceleration(1,gear,count,gameSpeed,&ratio,&smoother,4,0)*4*50;
        expected*=std::pow(1.0f-std::abs(expected)/50*(config.Drag/1000/2),50.0f/30.0f);
        Equal(speed,expected,"30-second real handling curve vs source");
        if (before!=state.CurrentGear) std::printf("shift t=%.2f gear=%u speedMs=%.6f\n",tick/30.0,state.CurrentGear,speed);
        if (tick==24 || tick==30 || tick==60 || tick==150 || tick==300 || tick==600 || tick==900)
            std::printf("curve t=%.2f nativeMs=%.6f sourceMs=%.6f gear=%u\n",tick/30.0,speed,expected,state.CurrentGear);
    }
    NativeTransmission::State release=state;
    Equal(landstal.DriveAcceleration(0,release,speed/50,1),0,"throttle release has zero thrust");
    Check(landstal.AirResistance(speed,1)<speed,"source air resistance coasts");
    Equal(landstal.AirResistance(-speed,1),-landstal.AirResistance(speed,1),"reverse drag symmetry");
    state={}; speed=0;
    for (int tick=0;tick<900;++tick) {
        speed+=landstal.DriveAcceleration(-1,state,speed/50,NativeTransmission::TimeStep)*4*50;
        speed=landstal.AirResistance(speed,NativeTransmission::TimeStep);
    }
    Check(state.CurrentGear==0 && speed<0 && speed>=landstal.MaxReverseVelocity*50-0.5f,"bounded reverse launch");
    std::printf("reverse t=30 speedMs=%.6f gear=%u\n",speed,state.CurrentGear);
    // Reproduce the removed realtime formula, not a regression expectation.
    float legacy=0;
    const float mass=std::stof(row[1]);
    for (int i=0;i<96;++i) {
        legacy+=config.EngineAcceleration/120;
        legacy=std::max(0.0f,legacy-(0.12f+config.Drag/mass*legacy*legacy)/120);
    }
    std::printf("legacy reproduction t=0.8 speedMs=%.6f\n",legacy);
    std::printf("native-transmission-probe PASS differentialCases=%d boundary=ordinary-car/no-cheat,flat-no-slip-aggregation,original-30Hz-limiter\n",comparisons);
}
